from django.urls import path
from . import views
from . import services

urlpatterns = [
    path('', services.admin_views_proxy(views.admin_index), name='admin_index'),
    path('account/login', views.account_login, name='admin_login'),
    path('account/logout', views.account_logout, name='admin_logout'),
    path('banner/list', services.admin_views_proxy(views.banner), name='admin_banner_list'),
    path('banner/main_slide/form', services.admin_views_proxy(views.main_slide_form), name='admin_main_slide_form'),
    path('banner/main_slide/form/<int:pk>', services.admin_views_proxy(views.main_slide_form, have_pk=True), name='admin_main_slide_edit'),
    path('banner/main_slide/delete/<int:pk>', services.admin_views_proxy(views.main_slide_delete, have_pk=True), name='admin_main_slide_delete'),
    path('banner/news_promo_slide/form', services.admin_views_proxy(views.news_promo_slide_form), name='admin_news_promo_slide_form'),
    path('banner/news_promo_slide/form/<int:pk>', services.admin_views_proxy(views.news_promo_slide_form, have_pk=True), name='admin_news_promo_slide_edit'),
    path('banner/news_promo_slide/delete/<int:pk>', services.admin_views_proxy(views.news_promo_slide_delete, have_pk=True), name='admin_news_promo_slide_delete'),
    path('banner/background/form', services.admin_views_proxy(views.background_banner_form), name='background_banner_form'),
    path('film/list', services.admin_views_proxy(views.film_list), name='admin_film_list'),
    path('film/delete/<int:pk>', services.admin_views_proxy(views.film_delete, have_pk=True), name='admin_film_delete'),
    path('film/form', services.admin_views_proxy(views.film_edit_form), name='admin_film_form'),
    path('film/form/<int:pk>', services.admin_views_proxy(views.film_edit_form, have_pk=True), name='admin_film_edit'),
    path('cinema/list', services.admin_views_proxy(views.cinema_list), name='admin_cinema_list'),
    path('cinema/form', services.admin_views_proxy(views.cinema_form), name='admin_cinema_form'),
    path('cinema/form/<int:pk>', services.admin_views_proxy(views.cinema_form, have_pk=True), name='admin_cinema_edit'),
    path('cinema/delete/<int:pk>', services.admin_views_proxy(views.cinema_delete, have_pk=True), name='admin_cinema_delete'),
    path('hall/form', services.admin_views_proxy(views.hall_form), name='admin_hall_form'),
    path('hall/form/<int:pk>', services.admin_views_proxy(views.hall_form, have_pk=True), name='admin_hall_edit'),
    path('hall/delete/<int:pk>', services.admin_views_proxy(views.hall_delete, have_pk=True), name='admin_hall_delete'),
    path('news/list', services.admin_views_proxy(views.news_list), name='admin_news_list'),
    path('news/form', services.admin_views_proxy(views.news_form), name='admin_news_form'),
    path('news/form/<int:pk>', services.admin_views_proxy(views.news_form, have_pk=True), name='admin_news_edit'),
    path('news/delete/<int:pk>', services.admin_views_proxy(views.news_delete, have_pk=True), name='admin_news_delete'),
    path('promotion/list', services.admin_views_proxy(views.promotion_list), name='admin_promotion_list'),
    path('promotion/form', services.admin_views_proxy(views.promotion_form), name='admin_promotion_form'),
    path('promotion/form/<int:pk>', services.admin_views_proxy(views.promotion_form, have_pk=True), name='admin_promotion_edit'),
    path('promotion/delete/<int:pk>', services.admin_views_proxy(views.promotion_delete, have_pk=True), name='admin_promotion_delete'),
    path('pages/list', services.admin_views_proxy(views.pages_list), name='admin_pages_list'),
    path('pages/main/info', services.admin_views_proxy(views.main_pages), name='admin_main_info'),
    path('pages/about/cinema', services.admin_views_proxy(views.about_cinema), name='admin_about_cinema'),
    path('pages/cafe/bar', services.admin_views_proxy(views.cafe_bar), name='admin_cafe_bar'),
    path('pages/vip/hall', services.admin_views_proxy(views.vip_hall), name='admin_vip_hall'),
    path('pages/ads', services.admin_views_proxy(views.ads), name='admin_ads'),
    path('pages/child/room', services.admin_views_proxy(views.child_room), name='admin_child_room'),
    path('pages/contact/list', services.admin_views_proxy(views.contact_list), name='admin_contact_list'),
    path('pages/contact/form', services.admin_views_proxy(views.contact_form), name='admin_contact_form'),
    path('pages/contact/edit/<int:pk>', services.admin_views_proxy(views.contact_form, have_pk=True), name='admin_contact_edit'),
    path('pages/contact/delete/<int:pk>', services.admin_views_proxy(views.contact_delete, have_pk=True), name='admin_contact_delete'),
    path('user/choose', services.admin_views_proxy(views.user_choose), name='admin_user_choose'),
    path('main/page', services.admin_views_proxy(views.main_pages), name='admin_main_page'),
    path('about/cinema', services.admin_views_proxy(views.about_cinema), name='admin_about_cinema'),
    path('users/list', services.admin_views_proxy(views.users_list), name='admin_users_list'),
    path('user/form', services.admin_views_proxy(views.user_form), name='admin_user_form'),
    path('user/form/<int:pk>', services.admin_views_proxy(views.user_form, have_pk=True), name='admin_user_edit'),
    path('user/delete/<int:pk>', services.admin_views_proxy(views.user_delete, have_pk=True), name='admin_user_delete'),
    path('mailing/choose', services.admin_views_proxy(views.user_choose), name='admin_user_choose'),
    path('mailing', services.admin_views_proxy(views.mailing), name='admin_mailing'),

]