# Generated by Django 3.1.5 on 2021-01-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название фильма')),
                ('slug', models.SlugField(max_length=55, unique=True)),
                ('description', models.TextField(verbose_name='Описание фильма')),
                ('main_image', models.ImageField(upload_to='media/images/film_poster')),
                ('image1', models.ImageField(upload_to='images/film_images', verbose_name='Первое изображение')),
                ('image2', models.ImageField(upload_to='images/film_images/', verbose_name='Второе изображение')),
                ('image3', models.ImageField(upload_to='images/film_images/', verbose_name='Третее изображение')),
                ('image4', models.ImageField(upload_to='images/film_images/', verbose_name='Четвёртое изображение')),
                ('image5', models.ImageField(upload_to='images/film_images/', verbose_name='Пятое изображение')),
                ('trailer_link', models.URLField(verbose_name='Ссылка на трейлер')),
                ('two_d', models.BooleanField(verbose_name='2Д')),
                ('three_d', models.BooleanField(verbose_name='3Д')),
                ('i_max', models.BooleanField(verbose_name='I_MAX')),
                ('duration', models.CharField(max_length=55, verbose_name='Длительность фильма')),
                ('first_night', models.DateField(verbose_name='Дата премьеры')),
            ],
        ),
    ]
