# Generated by Django 3.1.5 on 2021-01-27 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminLte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_name', models.CharField(max_length=255, verbose_name='Название сети кинотеатров')),
                ('cinema_description', models.TextField(verbose_name='Описание сети кинотеатров')),
                ('cinema_main_image', models.ImageField(upload_to='images/about/logo/', verbose_name='Логотип сети кинотеатров')),
                ('cinema_image1', models.ImageField(upload_to='images/about/', verbose_name='Первое изображение')),
                ('cinema_image2', models.ImageField(upload_to='images/about/', verbose_name='Второе изображение')),
                ('cinema_image3', models.ImageField(upload_to='images/about/', verbose_name='Третее изображение')),
                ('cinema_image4', models.ImageField(upload_to='images/about/', verbose_name='Четвёртое изображение')),
                ('cinema_image5', models.ImageField(upload_to='images/about/', verbose_name='Пятое изображение')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adv_name', models.CharField(max_length=255, verbose_name='Название рекламы')),
                ('adv_description', models.TextField(verbose_name='Описание рекламы')),
                ('adv_main_image', models.ImageField(upload_to='images/adv/logo/', verbose_name='Логотип рекламы')),
                ('adv_image1', models.ImageField(upload_to='images/adv/', verbose_name='Первое изображение')),
                ('adv_image2', models.ImageField(upload_to='images/adv/', verbose_name='Второе изображение')),
                ('adv_image3', models.ImageField(upload_to='images/adv/', verbose_name='Третее изображение')),
                ('adv_image4', models.ImageField(upload_to='images/adv/', verbose_name='Четвёртое изображение')),
                ('adv_image5', models.ImageField(upload_to='images/adv/', verbose_name='Пятое изображение')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BackgroundBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='images/background/', verbose_name='Изображение фона')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='', verbose_name='Изображение баннера')),
                ('banner_url', models.URLField(verbose_name='Ссылка под изображением')),
                ('banner_text', models.CharField(max_length=255, null=True, verbose_name='Описание изображения')),
            ],
        ),
        migrations.CreateModel(
            name='CafeBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafebar_name', models.CharField(max_length=255, verbose_name='Название кафе-бара')),
                ('cafebar_description', models.TextField(verbose_name='Описание кафе-бара')),
                ('cafebar_main_image', models.ImageField(upload_to='images/cafe_bar/logo/', verbose_name='Логотип кафе-бара')),
                ('cafebar_image1', models.ImageField(upload_to='images/cafe_bar/', verbose_name='Первое изображение')),
                ('cafebar_image2', models.ImageField(upload_to='images/cafe_bar/', verbose_name='Второе изображение')),
                ('cafebar_image3', models.ImageField(upload_to='images/cafe_bar/', verbose_name='Третее изображение')),
                ('cafebar_image4', models.ImageField(upload_to='images/cafe_bar/', verbose_name='Четвёртое изображение')),
                ('cafebar_image5', models.ImageField(upload_to='images/cafe_bar/', verbose_name='Пятое изображение')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChildRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255, verbose_name='Название детской комнаты')),
                ('room_description', models.TextField(verbose_name='Описание детской комнаты')),
                ('room_main_image', models.ImageField(upload_to='images/child_room/logo/', verbose_name='Логотип детской комнаты')),
                ('room_image1', models.ImageField(upload_to='images/child_room/', verbose_name='Первое изображение')),
                ('room_image2', models.ImageField(upload_to='images/child_room/', verbose_name='Второе изображение')),
                ('room_image3', models.ImageField(upload_to='images/child_room/', verbose_name='Третее изображение')),
                ('room_image4', models.ImageField(upload_to='images/child_room/', verbose_name='Четвёртое изображение')),
                ('room_image5', models.ImageField(upload_to='images/child_room/', verbose_name='Пятое изображение')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_name', models.CharField(max_length=255, verbose_name='Название кинотеатра')),
                ('cinema_description', models.TextField(verbose_name='Описание конотеатра')),
                ('cinema_condition', models.TextField(verbose_name='Условия кинотеатра')),
                ('cinema_logo', models.ImageField(upload_to='images/cinema/logo/', verbose_name='Логотип кинотеатра')),
                ('cinema_upper_banner', models.ImageField(upload_to='images/cinema/upper_banner/', verbose_name='Верхний баннер кинотеатра')),
                ('cinema_image1', models.ImageField(upload_to='images/cinema/', verbose_name='Первое изображение')),
                ('cinema_image2', models.ImageField(upload_to='images/cinema/', verbose_name='Второе изображение')),
                ('cinema_image3', models.ImageField(upload_to='images/cinema/', verbose_name='Третее изображение')),
                ('cinema_image4', models.ImageField(upload_to='images/cinema/', verbose_name='Четвёртое изображение')),
                ('cinema_image5', models.ImageField(upload_to='images/cinema/', verbose_name='Пятое изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=255, verbose_name='Название кинотеатра')),
                ('contact_address', models.TextField(verbose_name='Адрес кинотеатра')),
                ('contact_location', models.CharField(max_length=255, verbose_name='Координаты для карты')),
                ('contact_logo', models.ImageField(upload_to='images/contact/logo/', verbose_name='Лого')),
            ],
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_number1', models.IntegerField(null=True, verbose_name='Номер телефона')),
                ('tel_number2', models.IntegerField(null=True, verbose_name='Номер телефона')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MainSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_text', models.TextField(verbose_name='Текст слайда')),
                ('slide_image', models.ImageField(upload_to='images/main_slide/', verbose_name='Изображение слайда')),
                ('slide_url', models.URLField(verbose_name='Ссылка слайда')),
                ('slide_timer', models.IntegerField(verbose_name='Скорость вращения')),
                ('slider', models.TextField(default=True, verbose_name='none')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_name', models.CharField(max_length=255, verbose_name='Название новости')),
                ('news_description', models.TextField(verbose_name='Описание новости')),
                ('news_main_image', models.ImageField(upload_to='images/news/logo/', verbose_name='Логотип новости')),
                ('news_image1', models.ImageField(upload_to='images/news/', verbose_name='Первое изображение')),
                ('news_image2', models.ImageField(upload_to='images/news/', verbose_name='Второе изображение')),
                ('news_image3', models.ImageField(upload_to='images/news/', verbose_name='Третее изображение')),
                ('news_image4', models.ImageField(upload_to='images/news/', verbose_name='Четвёртое изображение')),
                ('news_image5', models.ImageField(upload_to='images/news/', verbose_name='Пятое изображение')),
                ('news_url', models.URLField(null=True, verbose_name='Ссылка на видео')),
                ('news_published_date', models.DateField(verbose_name='Дата публикации новости')),
                ('news_status', models.CharField(choices=[('ON', 'Active'), ('OFF', 'Inactive')], max_length=3, verbose_name='Выбор статуса')),
            ],
        ),
        migrations.CreateModel(
            name='NewsPromoSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_text', models.TextField(verbose_name='Текст слайда')),
                ('slide_image', models.ImageField(upload_to='images/news_promo/', verbose_name='Изображение слайда')),
                ('slide_url', models.URLField(verbose_name='Ссылка слайда')),
                ('slide_timer', models.IntegerField(verbose_name='Скорость вращения')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_name', models.CharField(max_length=255, verbose_name='Название акции')),
                ('promo_description', models.TextField(verbose_name='Описание акции')),
                ('promo_main_image', models.ImageField(upload_to='images/promotion/logo/', verbose_name='Логотип акции')),
                ('promo_image1', models.ImageField(upload_to='images/promotion/', verbose_name='Первое изображение')),
                ('promo_image2', models.ImageField(upload_to='images/promotion/', verbose_name='Второе изображение')),
                ('promo_image3', models.ImageField(upload_to='images/promotion/', verbose_name='Третее изображение')),
                ('promo_image4', models.ImageField(upload_to='images/promotion/', verbose_name='Четвёртое изображение')),
                ('promo_image5', models.ImageField(upload_to='images/promotion/', verbose_name='Пятое изображение')),
                ('promo_url', models.URLField(null=True, verbose_name='Ссылка на акцию')),
                ('promo_published_date', models.DateField(verbose_name='Дата публикации акции')),
                ('promo_status', models.CharField(choices=[('ON', 'Active'), ('OFF', 'Inactive')], max_length=3, verbose_name='Выбор статуса')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамиоия')),
                ('username', models.CharField(max_length=255, verbose_name='Юзернейм')),
                ('email', models.EmailField(max_length=254, verbose_name='Емаил')),
                ('phone', models.CharField(max_length=60, verbose_name='Номер телефона')),
                ('address', models.TextField(max_length=255, verbose_name='Адрес')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('password2', models.CharField(max_length=255, verbose_name='Пароль 2')),
                ('card_number', models.CharField(max_length=255, verbose_name='Номер карты')),
                ('language', models.CharField(choices=[('R', 'Rus'), ('U', 'Ukr')], default=1, max_length=1, verbose_name='Язык')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=1, max_length=1, verbose_name='Пол')),
                ('city', models.CharField(choices=[('OD', 'Одесса'), ('KY', 'Киев'), ('KHAR', 'Харьков')], max_length=4, verbose_name='Город')),
                ('date_of_birth', models.DateField(null=True, verbose_name='Дата рождения')),
                ('register_date', models.DateField(auto_now_add=True, null=True, verbose_name='дата регистрации')),
            ],
        ),
        migrations.CreateModel(
            name='VipHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_name', models.CharField(max_length=255, verbose_name='Название VIP-зала')),
                ('hall_description', models.TextField(verbose_name='Описание VIP-зала')),
                ('hall_main_image', models.ImageField(upload_to='images/vip_hall/logo/', verbose_name='Логотип VIP-зала')),
                ('hall_image1', models.ImageField(upload_to='images/vip_hall/', verbose_name='Первое изображение')),
                ('hall_image2', models.ImageField(upload_to='images/vip_hall/', verbose_name='Второе изображение')),
                ('hall_image3', models.ImageField(upload_to='images/vip_hall/', verbose_name='Третее изображение')),
                ('hall_image4', models.ImageField(upload_to='images/vip_hall/', verbose_name='Четвёртое изображение')),
                ('hall_image5', models.ImageField(upload_to='images/vip_hall/', verbose_name='Пятое изображение')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='film',
            name='slug',
        ),
        migrations.AlterField(
            model_name='film',
            name='main_image',
            field=models.ImageField(upload_to='images/film_poster'),
        ),
        migrations.CreateModel(
            name='CinemaHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_name', models.CharField(max_length=255, verbose_name='Название зала')),
                ('hall_description', models.TextField(verbose_name='Описание зала')),
                ('cinema_scheme', models.ImageField(upload_to='images/hall/logo/', verbose_name='Схема кинотеатра')),
                ('hall_upper_banner', models.ImageField(upload_to='images/hall/upper_banner/', verbose_name='Верхний баннер кинотеатра')),
                ('hall_image1', models.ImageField(upload_to='images/hall/', verbose_name='Первое изображение')),
                ('hall_image2', models.ImageField(upload_to='images/hall/', verbose_name='Второе изображение')),
                ('hall_image3', models.ImageField(upload_to='images/hall/', verbose_name='Третее изображение')),
                ('hall_image4', models.ImageField(upload_to='images/hall/', verbose_name='Четвёртое изображение')),
                ('hall_image5', models.ImageField(upload_to='images/hall/', verbose_name='Пятое изображение')),
                ('hall_scheme', models.ImageField(upload_to='images/hall/logo/', verbose_name='Схема зала')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminLte.cinema')),
            ],
        ),
    ]
