# Generated by Django 3.1.5 on 2021-01-23 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminLte', '0002_remove_film_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='', verbose_name='Изображение баннера')),
                ('banner_url', models.URLField(verbose_name='Ссылка под изображением')),
                ('banner_text', models.CharField(max_length=255, null=True, verbose_name='Описание изображения')),
            ],
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='media/images/film_poster', verbose_name='Главное изображение')),
                ('first_image', models.ImageField(upload_to='media/images/film_images', verbose_name='Первое изображение')),
                ('second_image', models.ImageField(upload_to='media/images/film_images', verbose_name='Второе изображение')),
                ('third_image', models.ImageField(upload_to='media/images/film_images', verbose_name='Третье изображение')),
                ('fourth_image', models.ImageField(upload_to='media/images/film_images', verbose_name='Четвёртое изображение')),
                ('fifth_image', models.ImageField(upload_to='media/images/film_images', verbose_name='Пятое изображение')),
            ],
        ),
        migrations.CreateModel(
            name='UpperBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_banner_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminLte.bannerimage')),
            ],
        ),
    ]
