# Generated by Django 3.1.5 on 2021-01-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminLte', '0003_remove_mainslide_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainslide',
            name='slide_timer',
            field=models.TextField(verbose_name='Скорость вращения'),
        ),
    ]
