# Generated by Django 3.1.5 on 2021-01-23 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminLte', '0003_bannerimage_imagegallery_upperbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_name', models.CharField(max_length=255, verbose_name='Название кинотеатра')),
                ('cinema_description', models.TextField(verbose_name='Описание конотеатра')),
                ('cinema_condition', models.TextField(verbose_name='Условия кинотеатра')),
                ('cinema_logo', models.ImageField(upload_to='media/images/cinema/logo/', verbose_name='Логотип кинотеатра')),
                ('cinema_upper_banner', models.ImageField(upload_to='media/images/cinema/upper_banner/', verbose_name='Верхний баннер кинотеатра')),
                ('cinema_image1', models.ImageField(upload_to='media/images/cinema/', verbose_name='Первое изображение')),
                ('cinema_image2', models.ImageField(upload_to='media/images/cinema/', verbose_name='Второе изображение')),
                ('cinema_image3', models.ImageField(upload_to='media/images/cinema/', verbose_name='Третее изображение')),
                ('cinema_image4', models.ImageField(upload_to='media/images/cinema/', verbose_name='Четвёртое изображение')),
                ('cinema_image5', models.ImageField(upload_to='media/images/cinema/', verbose_name='Пятое изображение')),
            ],
        ),
        migrations.CreateModel(
            name='CinemaHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_name', models.CharField(max_length=255, verbose_name='Название зала')),
                ('hall_description', models.TextField(verbose_name='Описание зала')),
                ('cinema_scheme', models.ImageField(upload_to='media/images/hall/logo/', verbose_name='Схема зала')),
                ('hall_upper_banner', models.ImageField(upload_to='media/images/hall/upper_banner/', verbose_name='Верхний баннер кинотеатра')),
                ('hall_image1', models.ImageField(upload_to='media/images/hall/', verbose_name='Первое изображение')),
                ('hall_image2', models.ImageField(upload_to='media/images/hall/', verbose_name='Второе изображение')),
                ('hall_image3', models.ImageField(upload_to='media/images/hall/', verbose_name='Третее изображение')),
                ('hall_image4', models.ImageField(upload_to='media/images/hall/', verbose_name='Четвёртое изображение')),
                ('hall_image5', models.ImageField(upload_to='media/images/hall/', verbose_name='Пятое изображение')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminLte.cinema')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=255, verbose_name='Название кинотеатра')),
                ('contact_address', models.TextField(verbose_name='Адрес кинотеатра')),
                ('contact_location', models.CharField(max_length=255, verbose_name='Координаты для карты')),
                ('contact_logo', models.ImageField(upload_to='media/images/contact/logo/', verbose_name='Лого')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_name', models.CharField(max_length=255, verbose_name='Название новости')),
                ('news_description', models.TextField(verbose_name='Описание новости')),
                ('news_main_image', models.ImageField(upload_to='media/images/news/logo/', verbose_name='Логотип новости')),
                ('news_image1', models.ImageField(upload_to='media/images/news/', verbose_name='Первое изображение')),
                ('news_image2', models.ImageField(upload_to='media/images/news/', verbose_name='Второе изображение')),
                ('news_image3', models.ImageField(upload_to='media/images/news/', verbose_name='Третее изображение')),
                ('news_image4', models.ImageField(upload_to='media/images/news/', verbose_name='Четвёртое изображение')),
                ('news_image5', models.ImageField(upload_to='media/images/news/', verbose_name='Пятое изображение')),
                ('news_url', models.URLField(null=True, verbose_name='Ссылка на видео')),
                ('news_published_date', models.DateField(verbose_name='Дата публикации новости')),
                ('news_status', models.BooleanField(default=False, verbose_name='Статус новости')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_name', models.CharField(max_length=255, verbose_name='Название акции')),
                ('promo_description', models.TextField(verbose_name='Описание акции')),
                ('promo_main_image', models.ImageField(upload_to='media/images/promotion/logo/', verbose_name='Логотип акции')),
                ('promo_image1', models.ImageField(upload_to='media/images/promotion/', verbose_name='Первое изображение')),
                ('promo_image2', models.ImageField(upload_to='media/images/promotion/', verbose_name='Второе изображение')),
                ('promo_image3', models.ImageField(upload_to='media/images/promotion/', verbose_name='Третее изображение')),
                ('promo_image4', models.ImageField(upload_to='media/images/promotion/', verbose_name='Четвёртое изображение')),
                ('promo_image5', models.ImageField(upload_to='media/images/promotion/', verbose_name='Пятое изображение')),
                ('promo_url', models.URLField(null=True, verbose_name='Ссылка на видео')),
                ('promo_published_date', models.DateField(verbose_name='Дата публикации акции')),
                ('promo_status', models.BooleanField(default=False, verbose_name='Статус акции')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамиоия')),
                ('username', models.CharField(max_length=255, verbose_name='Юзернейм')),
                ('email', models.EmailField(max_length=254, verbose_name='Емаил')),
                ('address', models.TextField(max_length=255, verbose_name='Адрес')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('password2', models.CharField(max_length=255, verbose_name='Пароль 2')),
                ('card_number', models.CharField(max_length=255, verbose_name='Номер карты')),
                ('language', models.CharField(choices=[('R', 'Rus'), ('U', 'Ukr')], max_length=1, verbose_name='Язык')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Пол')),
                ('city', models.CharField(choices=[('OD', 'Odessa'), ('KY', 'Kyiv'), ('KHAR', 'Kharkiv')], max_length=4, verbose_name='Город')),
            ],
        ),
        migrations.DeleteModel(
            name='ImageGallery',
        ),
        migrations.AlterField(
            model_name='upperbanner',
            name='upper_banner_image',
            field=models.ImageField(upload_to='media/images/upper_banner', verbose_name='Верхний баннер'),
        ),
    ]
