# Generated by Django 3.1.5 on 2021-01-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminLte', '0004_auto_20210123_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_status',
            field=models.CharField(choices=[('ON', 'Active'), ('OFF', 'Inactive')], max_length=3, verbose_name='Выбор статуса'),
        ),
    ]
