# Generated by Django 3.1.5 on 2021-01-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminLte', '0005_auto_20210125_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='cinema_image1',
            field=models.ImageField(upload_to='images/cinema/', verbose_name='Первое изображение'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='cinema_image2',
            field=models.ImageField(upload_to='images/cinema/', verbose_name='Второе изображение'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='cinema_image3',
            field=models.ImageField(upload_to='images/cinema/', verbose_name='Третее изображение'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='cinema_image4',
            field=models.ImageField(upload_to='images/cinema/', verbose_name='Четвёртое изображение'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='cinema_image5',
            field=models.ImageField(upload_to='images/cinema/', verbose_name='Пятое изображение'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='cinema_logo',
            field=models.ImageField(upload_to='images/cinema/logo/', verbose_name='Логотип кинотеатра'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='cinema_upper_banner',
            field=models.ImageField(upload_to='images/cinema/upper_banner/', verbose_name='Верхний баннер кинотеатра'),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='cinema_scheme',
            field=models.ImageField(upload_to='images/hall/logo/', verbose_name='Схема зала'),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='hall_image1',
            field=models.ImageField(upload_to='images/hall/', verbose_name='Первое изображение'),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='hall_image2',
            field=models.ImageField(upload_to='images/hall/', verbose_name='Второе изображение'),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='hall_image3',
            field=models.ImageField(upload_to='images/hall/', verbose_name='Третее изображение'),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='hall_image4',
            field=models.ImageField(upload_to='images/hall/', verbose_name='Четвёртое изображение'),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='hall_image5',
            field=models.ImageField(upload_to='images/hall/', verbose_name='Пятое изображение'),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='hall_upper_banner',
            field=models.ImageField(upload_to='images/hall/upper_banner/', verbose_name='Верхний баннер кинотеатра'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_logo',
            field=models.ImageField(upload_to='images/contact/logo/', verbose_name='Лого'),
        ),
        migrations.AlterField(
            model_name='film',
            name='main_image',
            field=models.ImageField(upload_to='images/film_poster'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_image1',
            field=models.ImageField(upload_to='images/news/', verbose_name='Первое изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_image2',
            field=models.ImageField(upload_to='images/news/', verbose_name='Второе изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_image3',
            field=models.ImageField(upload_to='images/news/', verbose_name='Третее изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_image4',
            field=models.ImageField(upload_to='images/news/', verbose_name='Четвёртое изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_image5',
            field=models.ImageField(upload_to='images/news/', verbose_name='Пятое изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_main_image',
            field=models.ImageField(upload_to='images/news/logo/', verbose_name='Логотип новости'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promo_image1',
            field=models.ImageField(upload_to='promotion/', verbose_name='Первое изображение'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promo_image2',
            field=models.ImageField(upload_to='promotion/', verbose_name='Второе изображение'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promo_image3',
            field=models.ImageField(upload_to='promotion/', verbose_name='Третее изображение'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promo_image4',
            field=models.ImageField(upload_to='promotion/', verbose_name='Четвёртое изображение'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promo_image5',
            field=models.ImageField(upload_to='promotion/', verbose_name='Пятое изображение'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promo_main_image',
            field=models.ImageField(upload_to='promotion/logo/', verbose_name='Логотип акции'),
        ),
        migrations.AlterField(
            model_name='upperbanner',
            name='upper_banner_image',
            field=models.ImageField(upload_to='images/upper_banner', verbose_name='Верхний баннер'),
        ),
    ]
