# Generated by Django 3.1.5 on 2021-01-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminLte', '0005_auto_20210127_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainslide',
            name='slide_image',
            field=models.ImageField(upload_to='images/main_slide/', verbose_name='Изображение слайда'),
        ),
    ]
