# Generated by Django 3.1.5 on 2021-01-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminLte', '0006_auto_20210125_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='promo_image1',
            field=models.ImageField(upload_to='images/promotion/', verbose_name='Первое изображение'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promo_image2',
            field=models.ImageField(upload_to='images/promotion/', verbose_name='Второе изображение'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promo_image3',
            field=models.ImageField(upload_to='images/promotion/', verbose_name='Третее изображение'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promo_image4',
            field=models.ImageField(upload_to='images/promotion/', verbose_name='Четвёртое изображение'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promo_image5',
            field=models.ImageField(upload_to='images/promotion/', verbose_name='Пятое изображение'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promo_main_image',
            field=models.ImageField(upload_to='images/promotion/logo/', verbose_name='Логотип акции'),
        ),
    ]
