# Generated by Django 3.1.5 on 2021-01-26 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminLte', '0006_auto_20210125_2030'),
        ('adminLte', '0007_auto_20210125_1923'),
    ]

    operations = [
    ]
