# Generated by Django 3.1.5 on 2021-01-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminLte', '0007_auto_20210125_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemahall',
            name='hall_scheme',
            field=models.ImageField(default=0, upload_to='images/hall/logo/', verbose_name='Схема зала'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=0, max_length=60, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
