# Generated by Django 3.1.5 on 2021-01-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminLte', '0008_auto_20210126_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
    ]
