# Generated by Django 3.1.5 on 2021-01-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminLte', '0009_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(choices=[('OD', 'Одесса'), ('KY', 'Киев'), ('KHAR', 'Харьков')], max_length=4, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=1, max_length=1, verbose_name='Пол'),
        ),
    ]
