# Generated by Django 3.1.5 on 2021-01-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminLte', '0010_auto_20210126_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('R', 'Rus'), ('U', 'Ukr')], default=1, max_length=1, verbose_name='Язык'),
        ),
    ]
