# Generated by Django 3.1.5 on 2021-01-26 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminLte', '0010_aboutcinemas_advertising_cafebar_childroom_mainpage_viphall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainpage',
            old_name='number1',
            new_name='tel_number1',
        ),
        migrations.RenameField(
            model_name='mainpage',
            old_name='number2',
            new_name='tel_number2',
        ),
    ]
