# Generated by Django 3.1.5 on 2021-01-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminLte', '0011_auto_20210126_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='register_date',
            field=models.DateField(auto_created=True, null=True, verbose_name='дата регистрации'),
        ),
    ]
