# Generated by Django 3.1.5 on 2021-01-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminLte', '0011_auto_20210126_1728'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutCinemas',
            new_name='AboutCinema',
        ),
        migrations.RenameField(
            model_name='aboutcinema',
            old_name='cinemas_description',
            new_name='cinema_description',
        ),
        migrations.RenameField(
            model_name='aboutcinema',
            old_name='cinemas_image1',
            new_name='cinema_image1',
        ),
        migrations.RenameField(
            model_name='aboutcinema',
            old_name='cinemas_image2',
            new_name='cinema_image2',
        ),
        migrations.RenameField(
            model_name='aboutcinema',
            old_name='cinemas_image3',
            new_name='cinema_image3',
        ),
        migrations.RenameField(
            model_name='aboutcinema',
            old_name='cinemas_image4',
            new_name='cinema_image4',
        ),
        migrations.RenameField(
            model_name='aboutcinema',
            old_name='cinemas_image5',
            new_name='cinema_image5',
        ),
        migrations.RenameField(
            model_name='aboutcinema',
            old_name='cinemas_main_image',
            new_name='cinema_main_image',
        ),
        migrations.RenameField(
            model_name='aboutcinema',
            old_name='cinemas_name',
            new_name='cinema_name',
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='tel_number1',
            field=models.IntegerField(verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='tel_number2',
            field=models.IntegerField(verbose_name='Номер телефона'),
        ),
    ]
