# Generated by Django 3.1.5 on 2021-01-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminLte', '0012_user_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='register_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='дата регистрации'),
        ),
    ]
