# Generated by Django 3.1.5 on 2021-01-26 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminLte', '0009_auto_20210126_1622'),
        ('adminLte', '0013_auto_20210126_2125'),
    ]

    operations = [
    ]
