# Generated by Django 3.1.5 on 2021-01-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminLte', '0014_merge_20210127_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_name', models.CharField(max_length=255, verbose_name='Название сети кинотеатров')),
                ('cinema_description', models.TextField(verbose_name='Описание сети кинотеатров')),
                ('cinema_main_image', models.ImageField(upload_to='images/about/logo/', verbose_name='Логотип сети кинотеатров')),
                ('cinema_image1', models.ImageField(upload_to='images/about/', verbose_name='Первое изображение')),
                ('cinema_image2', models.ImageField(upload_to='images/about/', verbose_name='Второе изображение')),
                ('cinema_image3', models.ImageField(upload_to='images/about/', verbose_name='Третее изображение')),
                ('cinema_image4', models.ImageField(upload_to='images/about/', verbose_name='Четвёртое изображение')),
                ('cinema_image5', models.ImageField(upload_to='images/about/', verbose_name='Пятое изображение')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adv_name', models.CharField(max_length=255, verbose_name='Название рекламы')),
                ('adv_description', models.TextField(verbose_name='Описание рекламы')),
                ('adv_main_image', models.ImageField(upload_to='images/adv/logo/', verbose_name='Логотип рекламы')),
                ('adv_image1', models.ImageField(upload_to='images/adv/', verbose_name='Первое изображение')),
                ('adv_image2', models.ImageField(upload_to='images/adv/', verbose_name='Второе изображение')),
                ('adv_image3', models.ImageField(upload_to='images/adv/', verbose_name='Третее изображение')),
                ('adv_image4', models.ImageField(upload_to='images/adv/', verbose_name='Четвёртое изображение')),
                ('adv_image5', models.ImageField(upload_to='images/adv/', verbose_name='Пятое изображение')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CafeBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafebar_name', models.CharField(max_length=255, verbose_name='Название кафе-бара')),
                ('cafebar_description', models.TextField(verbose_name='Описание кафе-бара')),
                ('cafebar_main_image', models.ImageField(upload_to='images/cafe_bar/logo/', verbose_name='Логотип кафе-бара')),
                ('cafebar_image1', models.ImageField(upload_to='images/cafe_bar/', verbose_name='Первое изображение')),
                ('cafebar_image2', models.ImageField(upload_to='images/cafe_bar/', verbose_name='Второе изображение')),
                ('cafebar_image3', models.ImageField(upload_to='images/cafe_bar/', verbose_name='Третее изображение')),
                ('cafebar_image4', models.ImageField(upload_to='images/cafe_bar/', verbose_name='Четвёртое изображение')),
                ('cafebar_image5', models.ImageField(upload_to='images/cafe_bar/', verbose_name='Пятое изображение')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChildRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255, verbose_name='Название детской комнаты')),
                ('room_description', models.TextField(verbose_name='Описание детской комнаты')),
                ('room_main_image', models.ImageField(upload_to='images/child_room/logo/', verbose_name='Логотип детской комнаты')),
                ('room_image1', models.ImageField(upload_to='images/child_room/', verbose_name='Первое изображение')),
                ('room_image2', models.ImageField(upload_to='images/child_room/', verbose_name='Второе изображение')),
                ('room_image3', models.ImageField(upload_to='images/child_room/', verbose_name='Третее изображение')),
                ('room_image4', models.ImageField(upload_to='images/child_room/', verbose_name='Четвёртое изображение')),
                ('room_image5', models.ImageField(upload_to='images/child_room/', verbose_name='Пятое изображение')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_number1', models.IntegerField(verbose_name='Номер телефона')),
                ('tel_number2', models.IntegerField(verbose_name='Номер телефона')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VipHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_name', models.CharField(max_length=255, verbose_name='Название VIP-зала')),
                ('hall_description', models.TextField(verbose_name='Описание VIP-зала')),
                ('hall_main_image', models.ImageField(upload_to='images/vip_hall/logo/', verbose_name='Логотип VIP-зала')),
                ('hall_image1', models.ImageField(upload_to='images/vip_hall/', verbose_name='Первое изображение')),
                ('hall_image2', models.ImageField(upload_to='images/vip_hall/', verbose_name='Второе изображение')),
                ('hall_image3', models.ImageField(upload_to='images/vip_hall/', verbose_name='Третее изображение')),
                ('hall_image4', models.ImageField(upload_to='images/vip_hall/', verbose_name='Четвёртое изображение')),
                ('hall_image5', models.ImageField(upload_to='images/vip_hall/', verbose_name='Пятое изображение')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='cinema_scheme',
            field=models.ImageField(upload_to='images/hall/logo/', verbose_name='Схема кинотеатра'),
        ),
    ]
