# Generated by Django 3.1.5 on 2021-01-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminLte', '0015_auto_20210127_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='tel_number1',
            field=models.IntegerField(null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='tel_number2',
            field=models.IntegerField(null=True, verbose_name='Номер телефона'),
        ),
    ]
