# Generated by Django 3.1.5 on 2021-01-27 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminLte', '0016_auto_20210127_1044'),
        ('adminLte', '0012_auto_20210126_1952'),
    ]

    operations = [
    ]
